############################################################
# 开发环境容器
# 基于Ubuntu 16.04
############################################################
FROM ubuntu:16.04

MAINTAINER meis5@qq.com

ENV HOME /root
WORKDIR $HOME

# 设置正确的语言信息
RUN locale-gen en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
EXPOSE 80 443

